### ISSUE TITLE
Error al ejecutar cliente desde Program Files

### ISSUE THREAD

**Issue by plusin** [ao-libre/ao-autoupdate#19]
Me ha pasado que si ejecuto el cliente desde el autoupdate todo funciona ok, pero si intento ejecutar el cliente desde el ejecutable directo de la carpeta Cliente, aparece el error adjunto.

![errorclientee](https://user-images.githubusercontent.com/7727108/88506974-a7d2ea00-cfb1-11ea-8ed0-f1f714259399.png)

**Comment by juandpr** [comment]
Muy probablemente el autoupdate se ejecute como admin, por lo tanto ejecuta el cliente como administrador tambien. Probá ejecutar el cliente como administrador (click derecho -> ejecutar como administrador) y fijate si sigue pasando.

**Comment by plusin** [comment]
Arranco, gracias @juandpr
